# statistics<-c(
#   "Diameter"="Diameter\tdiameter(igraph)",
#   "Radius"="Radius\tradius(igraph)",
#   "Density"="Density\tgraph.density(igraph)",
#   "Diversity (only for weighted networks"="Diversity\tgraph.diversity(igraph)",
#   "Modularity"="Modularity\tmodularity(igraph)",
#   "Average number of Neighbors"="Average number of Neighbors\tdegree.distribution(igraph)",
#   "Average nearest neighbor degree"="Average nearest neighbor degree\tgraph.knn(igraph)",
#   "Number of Edges"="Number of Edges\tE(igraph)",
#   "Number of self loops"="Number of self loops\tsum(is.loop(igraph))",
#   "Average Alpha Centrality"="Average Alpha Centrality\tmean(alpha.centrality(igraph))",
#   "Average Kleinberg’s centrality"="Average Kleinberg’s centrality\tmean(authority.score(igraph)$vector)",
#   "Average Eccentricity"="Average Eccentricity\tmean(eccentricity(igraph))",
#   "Average Eigenvector Centrality"="Average Eigenvector Centrality\tmean(evcent(igraph)$vector)",
#   "Is directed acyclic graph?"="Is directed acyclic graph?\tis.dag(igraph)",
#   "Is Directed?"="Is Directed?\tis.directed(igraph)",
#   "Is chordal? "="Is chordal?\tis.chordal(igraph)",
#   "Count adjacenct triangles"="Count adjacenct triangles\tadjacent.triangles(igraph)",
#   "Find Bonacich alpha centrality scores (slow)"="Find Bonacich alpha centrality\tbonpow(igraph)",
#   "Assortativity coefficient (metadata)"="Assortativity coefficient\tassortativity(igraph)",
#   "Assortativity degree"="Assortativity degree\tassortativity.degree(igraph)",
#   "Assortativity nominal (metadata)"="Assortativity nominal\tassortativity.nominal(igraph)",
#   "Average path length"="Average path length\taverage.path.length(igraph)",
#   "Betweenness"="Betweenness\tbetweenness(igraph)",
#   "Betweenness estimate (cutoff)"="Betweenness estimate\tbetweenness.estimate(igraph)",
#   "Centralization.betweenness"="Centralization.betweenness\tcentralization.betweenness(igraph)",
#   "Centralization.betweenness.tmax"="Centralization.betweenness.tmax\tcentralization.betweenness.tmax(igraph)",
#   "Centralization.closeness"="Centralization.closeness\tcentralization.closeness(igraph)",
#   "Centralization.closeness.tmax"="Centralization.closeness.tmax\tcentralization.closeness.tmax(igraph)",
#   "Centralization.degree"="Centralization.degree\tcentralization.degree(igraph)",
#   "Centralization.degree.tmax"="Centralization.degree.tmax\tcentralization.degree.tmax(igraph)",
#   "Centralization.evcent"="Centralization.evcent\tcentralization.evcent(igraph)",
#   "Centralization.evcent.tmax"="Centralization.evcent.tmax\tcentralization.evcent.tmax(igraph)",
#   "Clique.number"="Clique.number\tclique.number(igraph)",
#   "Cliques"="Cliques\tcliques(igraph)",
#   "Closeness"="Closeness\tcloseness(igraph)",
#   "Closeness.estimate (cutoff)"="Closeness.estimate\tcloseness.estimate(igraph)",
#   "Cluster.distribution"="Cluster.distribution\tcluster.distribution(igraph)",
#   "Clusters"="Clusters\tclusters(igraph)",
#   "Graph.knn"="Graph.knn\tgraph.knn(igraph)",
#   "Graph.maxflow (source vertex)"="Graph.maxflow\tgraph.maxflow(igraph)",
#   "Graph.mincut"="Graph.mincut\tgraph.mincut(igraph)",
#   "Graph.strength"="Graph.strength\tgraph.strength(igraph)",
#   "Maximum.cardinality.search"="Maximum.cardinality.search\tmaximum.cardinality.search(igraph)",
#   "Neighborhood.size (integer order)"="Neighborhood.size\tneighborhood.size(igraph)",
#   "No.clusters"="No.clusters\tno.clusters(igraph)",
#   "Subgraph.centrality"="Subgraph.centrality\tsubgraph.centrality(igraph)",
#   "Transitivity"="Transitivity\ttransitivity(igraph)"
# )
# 
# 
# selected_statistics <-c(
#   "Diameter\tdiameter(igraph)",
#   "Radius\tradius(igraph)",
#   "Centralization\tcentralization.degree(igraph)",
#   "Density\tgraph.density(igraph)"
#   )

statistics <- c(
  "Number of Edges" = "Number of Edges\tecount(igraph)",
  "Number of Nodes" = "Number of Nodes\tvcount(igraph)",
  "Diameter" = "Diameter\tdiameter(igraph)",
  "Radius" = "Radius\tradius(igraph)",
  "Density" = "Density\tgraph.density(igraph)",
  "Average path length" = "Average path length\taverage.path.length(igraph)",
  "Clustering Coefficient" = "Clustering Coefficient\ttransitivity(igraph)",
  "Modularity" = "Modularity\tmodularity(igraph,membership(walktrap.community(igraph)))",
  "Number of self loops" = "Number of self loops\tsum(is.loop(igraph))",
  #  "Average Alpha Centrality"="Average Alpha Centrality\tmean(alpha.centrality(igraph))",
  #  "Average Kleinberg’s centrality"="Average Kleinberg’s centrality\tmean(authority.score(igraph)$vector)",
  "Average Eccentricity" = "Average Eccentricity\tmean(eccentricity(igraph))",
  "Average Eigenvector Centrality" = "Average Eigenvector Centrality\tmean(evcent(igraph)$vector)",
  "Assortativity degree" = "Assortativity degree\tassortativity.degree(igraph)",
  #  "Clique number"="Clique number\tclique.number(igraph)",
  #  "Number of clusters"="No clusters\tno.clusters(igraph)",
  "Is directed acyclic graph?" = "Is directed acyclic graph?\tas.logical(is.dag(igraph))",
  "Is Directed?" = "Is Directed?\tas.logical(is.directed(igraph))",
  "Is chordal? " = "Is chordal?\tas.logical(is.chordal(igraph)$chordal)",
  "Average number of Neighbors" = "Average number of Neighbors\t(centr_eigen(igraph)$centralization)",
  #  "Average nearest neighbor degree"="Average nearest neighbor degree\tgraph.knn(igraph)",
  #  "Count adjacenct triangles"="Count adjacenct triangles\tadjacent.triangles(igraph)",
  #  "Find Bonacich alpha centrality scores (slow)"="Find Bonacich alpha centrality\tbonpow(igraph)",
  #  "Assortativity coefficient"="Assortativity coefficient\tassortativity.degree(igraph)",
  "Centralization betweenness" = "Centralization.betweenness\tcentralization.betweenness(igraph)$centralization",
  "Centralization closeness" = "Centralization.closeness\tcentralization.closeness(igraph)$centralization",
  "Centralization degree" = "Centralization.degree\tcentralization.degree(igraph)$centralization",
  #  "Centralization evcent"="Centralization.evcent\tcentralization.evcent(igraph)$centralization",
  #  "Cliques"="Cliques\tlength(cliques(igraph))",
  #  "Closeness"="Closeness\tcloseness(igraph)",
  #  "Cluster distribution"="Cluster.distribution\tcluster.distribution(igraph)",
  #  "Clusters"="Clusters\tclusters(igraph)$no",
  #  "Graph knn"="Graph.knn\tgraph.knn(igraph)",
  #  "Graph maxflow (source vertex)"="Graph.maxflow\tgraph.maxflow(igraph)",
  "Graph mincut" = "Graph.mincut\tgraph.mincut(igraph)",
  "Motifs-3" = "Motifs-3\tcount_motifs(igraph,3)",
  "Motifs-4" = "Motifs-4\tcount_motifs(igraph,4)"  
  #  "Graph strength"="Graph.strength\tgraph.strength(igraph)",
  #  "Neighborhood size (integer order)"="Neighborhood.size\tneighborhood.size(igraph)",
  #  "Subgraph centrality"="Subgraph.centrality\tsubgraph.centrality(igraph)",
  #  "Maximum cardinality search"="Maximum.cardinality.search\tmaximum.cardinality.search(igraph)"
)
selected_statistics <- c("Number of Edges" = "Number of Edges\tecount(igraph)",
                         "Number of Nodes" = "Number of Nodes\tvcount(igraph)")